### PR TITLE
get the correct NCDOMAIN from overwrite.cli.url

### LINKED ISSUE #1405: Improve the way domain name is entered for Documentserver
As it is right now, you need to add cloud\.yourdomain\.com in the inputbox. Before the change you could just copy what was already written, or only change the parts that needed changing. Now there's a big risk of failure, even I failed as the check thought that I didn't use TLS on the main domain.

We should therefore make it possible to only type the domain itself, and codewise fix the \ \ \ stuff.

The user should only have to type the real domain.

We should also add a `yesno_box` to ask if the domain is correct.

### PR DESCRIPTION
**Pull request by szaimen**
should fix #1405

### CODE REVIEW

**Comment by szaimen** [comment]
@enoch85 I haven't tested the whole scripts but it should already work.

**Comment by enoch85** [comment]
We should do it like we do in OnlyOffice for the variable (https://github.com/nextcloud/vm/blob/master/apps/onlyoffice_docker.sh#L163) and remove from lib.

File: apps/onlyoffice_docker.sh [hunk 1]
```diff
@@ -160,7 +160,7 @@ fi
 # OnlyOffice URL (onlyoffice.sh)
 SUBDOMAIN=$(input_box "OnlyOffice subdomain e.g: office.yourdomain.com\n\nNOTE: This domain must be different than your Nextcloud domain. They can however be hosted on the same server, but would require seperate DNS entries.")
 # Nextcloud Main Domain (onlyoffice.sh)
-NCDOMAIN=$(input_box "Nextcloud domain, make sure it looks like this: cloud\\.yourdomain\\.com")
+NCDOMAIN=$(occ_command_no_check config:system:get overwrite.cli.url | sed 's#https://##;s#/##')
```
Comment (enoch85) [inline apps/onlyoffice_docker.sh:163]: What if that value isn't set? Better to hardcode it if you ask me.

Comment (szaimen) [reply apps/onlyoffice_docker.sh:163]: The overwrite.cli.url must be set, else Nextcloud doesn't work correctly. So I am sure that this works.

Comment (enoch85) [reply apps/onlyoffice_docker.sh:163]: If the user haven't run the LE script the domain is 'localhost'. Have you tested that as well so that it doesn't bug out if nothing is set to something not being a domain?

Comment (szaimen) [reply apps/onlyoffice_docker.sh:163]: No, I haven't tested this detail. But my testing in the past has showed that the curl command always fails if self singed certificates are used which is the case here.

Comment (szaimen) [reply apps/onlyoffice_docker.sh:163]: I've tested this just now and can confirm my previous comment

**Comment by szaimen** [comment]
> We should do it like we do in OnlyOffice for the variable (https://github.com/nextcloud/vm/blob/master/apps/onlyoffice_docker.sh#L163) and remove from lib.

done 👍

**Comment by enoch85** [comment]
OK, so is this ready to merge?

**Comment by szaimen** [comment]
I would say yes, but still haven't tested the whole scripts.

**Comment by enoch85** [comment]
Just tested the varaiable, and it doesn't work since it needs to be `\\` and not `\`.

File: apps/collabora_docker.sh [hunk 2]
```diff
@@ -142,12 +142,16 @@ then
     occ_command app:remove onlyoffice
 fi
 
-# shellcheck disable=2034,2059
-true
+# Collabora Docker URL (collabora.sh
+SUBDOMAIN=$(input_box "Collabora subdomain eg: office.yourdomain.com\n\nNOTE: This domain must be different than your Nextcloud domain. They can however be hosted on the same server, but would require seperate DNS entries.")
+# Nextcloud Main Domain (collabora.sh)
+NCDOMAIN=$(occ_command_no_check config:system:get overwrite.cli.url | sed 's#https://##;s#/##')
```
Comment (enoch85) [inline apps/collabora_docker.sh:148]: Please use | instead of # as we do that everywhere else.

File: apps/onlyoffice_docker.sh (hunk 1 above)
Comment (enoch85) [inline apps/onlyoffice_docker.sh:163]: | instead of # please

**Comment by enoch85** [comment]
When comments are fixed, I will merge.

File: apps/collabora_docker.sh (hunk 2 above)
Comment (szaimen) [reply apps/collabora_docker.sh]: fixed

File: apps/onlyoffice_docker.sh (hunk 1 above)
Comment (szaimen) [reply apps/onlyoffice_docker.sh]: fixed
