### PR TITLE
Fix spelling in VM

### LINKED ISSUE #1577: Native English speakers are wanted!
Both @szaimen and I are not native English speakers, and the text in the inform boxes might be a bit off in some places.

We would really need someone that looked through all the `msg_box`, `yesno_yes`, `yesno_no` and other informative boxes in general that are presented to the users in the scripts.

Payment can be discussed when the PR is merged.

Thanks!

### PR DESCRIPTION
**Pull request by lantrix**
Resolves #1577 

Spelling corrected in:

- markdown
- shell scripts
- php

actually all files in the end that I could open in a text editor.

Changes only made in:

- Comments
- Output messages

### CODE REVIEW

File: lib.sh [hunk 1]
```diff
@@ -1225,7 +1225,7 @@ spinner_loading() {
     while kill -0 $pid 2>/dev/null
     do
         i=$(( (i+1) %4 ))
-        printf "\r[${spin:$i:1}] " # Add text here, something like "Please be paitent..." maybe?
+        printf "\r[${spin:$i:1}] " # Add text here, something like "Please be patient..." maybe?
```
Comment (enoch85) [inline lib.sh:1228]: @szaimen Do you have time to take a look at this?

**Comment by enoch85** [comment]
WOW, thanks @lantrix! This is huge! <3

**Comment by szaimen** [comment]
@lantrix Thank you very much from my side, too! This is really great! :)
